// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcGeoMeansDense
NumericVector calcGeoMeansDense(NumericMatrix x);
RcppExport SEXP _ascend_calcGeoMeansDense(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcGeoMeansDense(x));
    return rcpp_result_gen;
END_RCPP
}
// calcNormFactorDense
NumericVector calcNormFactorDense(NumericMatrix x, NumericVector y);
RcppExport SEXP _ascend_calcNormFactorDense(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(calcNormFactorDense(x, y));
    return rcpp_result_gen;
END_RCPP
}
// applyRLE
NumericMatrix applyRLE(NumericMatrix x, NumericVector y);
RcppExport SEXP _ascend_applyRLE(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(applyRLE(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convertSparse
arma::sp_mat convertSparse(S4 mat);
RcppExport SEXP _ascend_convertSparse(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(convertSparse(mat));
    return rcpp_result_gen;
END_RCPP
}
// calcGeoMeansSparse
NumericVector calcGeoMeansSparse(S4 sparseMatrix);
RcppExport SEXP _ascend_calcGeoMeansSparse(SEXP sparseMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sparseMatrix(sparseMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(calcGeoMeansSparse(sparseMatrix));
    return rcpp_result_gen;
END_RCPP
}
// calcNormFactorSparse
NumericVector calcNormFactorSparse(S4 sparseMatrix, NumericVector geoMeans);
RcppExport SEXP _ascend_calcNormFactorSparse(SEXP sparseMatrixSEXP, SEXP geoMeansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sparseMatrix(sparseMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type geoMeans(geoMeansSEXP);
    rcpp_result_gen = Rcpp::wrap(calcNormFactorSparse(sparseMatrix, geoMeans));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ascend_calcGeoMeansDense", (DL_FUNC) &_ascend_calcGeoMeansDense, 1},
    {"_ascend_calcNormFactorDense", (DL_FUNC) &_ascend_calcNormFactorDense, 2},
    {"_ascend_applyRLE", (DL_FUNC) &_ascend_applyRLE, 2},
    {"_ascend_convertSparse", (DL_FUNC) &_ascend_convertSparse, 1},
    {"_ascend_calcGeoMeansSparse", (DL_FUNC) &_ascend_calcGeoMeansSparse, 1},
    {"_ascend_calcNormFactorSparse", (DL_FUNC) &_ascend_calcNormFactorSparse, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ascend(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
