################################################################################
#
# ascend_cellranger.R
# description: Functions related to the loading and prepation of Chromium
# data generated by the Cell Ranger pipeline
#
################################################################################

#' loadCellRanger
#' 
#' Automatically loads and prepares data from a folder containing Cell Ranger
#' output. Filtered data should be used as raw data is too large for most 
#' desktop systems. 
#' 
#' @param x Path to Cell Ranger filtered output (eg. outs/filtered_gene_bc_matrices_mex/GRCh38p7)
#' 
#' @return A list containing the following objects: gene_info, cell_info, counts
#' @include ascend_objects.R
#' @include ascend_methods.R
#' @importFrom S4Vectors DataFrame
#' @export
loadCellRanger <- function(x){
  matrix_file <- joinPaths(c(x, "matrix.mtx"))
  barcodes_file <- joinPaths(c(x, "barcodes.tsv"))
  genes_file <- joinPaths(c(x, "genes.tsv"))
  
  # Create things from scratch to ensure nothing is missed
  barcodes <- read.csv(barcodes_file, header = FALSE, sep = "\t", 
                       stringsAsFactors = FALSE)
  colnames(barcodes) <- c("cell_barcode")
  barcodes$batch <- as.numeric(unlist(
    lapply(strsplit(as.character(barcodes$cell_barcode), "-"), `[`, 2)))
  
  genes <- read.csv(genes_file, 
                    header = FALSE, 
                    sep = "\t", 
                    stringsAsFactors = FALSE)
  
  colnames(genes) <- c("ensembl_gene_id", "gene_id")
  genes$gene_id <- make.unique(genes$gene_id)
  genes <- genes[ , c("gene_id", "ensembl_gene_id")]
  
  sparse_matrix <- Matrix::readMM(matrix_file)
  expression_matrix <- as.matrix(sparse_matrix)
  colnames(expression_matrix) <- barcodes[, 1]
  rownames(expression_matrix) <- genes[, 1]
  
  # Create EMSet
  controls <- list(Mt = grep("^Mt-", genes[,"gene_id"], ignore.case = TRUE, value = TRUE), 
                   Rb = grep("^Rps|^Rpl", genes[, "gene_id"], ignore.case = TRUE, value = TRUE))
  
  object <- newEMSet(assays = list(counts = expression_matrix), 
                         colInfo = S4Vectors::DataFrame(barcodes),
                         rowInfo = S4Vectors::DataFrame(genes),
                         controls = controls)
  
  return(object)
}
